version: "3"
services:
  db:
    image: postgres:12.6
    env_file:
      - db.env
    container_name: account_db
    volumes:
      - "$PWD/data:/var/lib/postgresql/data"
    networks:
      - account_net

  api:
    build:
      context: api
    container_name: account_api
    tty: true
    volumes:
      - "$PWD/api/migration:/opt/migration"
      - "$PWD/api/project:/opt/project"
    ports:
      - 8080:8080
    networks:
      - account_net

networks:
  account_net:
